# Generated by Django 6.0.3 on 2026-03-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
