# Generated by Django 6.0.3 on 2026-04-03 07:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_match_prediction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_number']},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['-number']},
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('fixture', 'Fixture'), ('live', 'Live'), ('result', 'Result'), ('postponed', 'Postponed'), ('void', 'Void')], default='fixture', max_length=10),
        ),
        migrations.AddField(
            model_name='week',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text="The Saturday this week's matches are played"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pool.league'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='prediction',
            field=models.CharField(blank=True, choices=[('fixture', 'Fixture'), ('live', 'Live'), ('result', 'Result'), ('postponed', 'Postponed'), ('void', 'Void')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('week', 'match_number')},
        ),
    ]
