# Generated by Django 6.0.3 on 2026-04-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0005_alter_match_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('column', models.CharField(choices=[('quick_links', 'Quick Links'), ('partner_sites', 'Partner Sites')], default='quick_links', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number appears first')),
                ('is_active', models.BooleanField(default=True)),
                ('opens_in_new_tab', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['column', 'order'],
            },
        ),
    ]
