# Generated by Django 6.0.3 on 2026-04-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0006_footerlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerlink',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='footerlink',
            name='column',
        ),
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.AddField(
            model_name='match',
            name='day',
            field=models.CharField(blank=True, choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('EKO', 'EKO - Early Kick Off'), ('LKO', 'LKO - Late Kick Off')], max_length=10),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
