# Generated by Django 6.0.3 on 2026-04-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0007_alter_footerlink_options_remove_footerlink_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Show this week on the homepage by default'),
        ),
        migrations.AddField(
            model_name='week',
            name='is_current_fixture',
            field=models.BooleanField(default=False, help_text='Show this week on the fixtures page by default'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='opens_in_new_tab',
            field=models.BooleanField(default=True),
        ),
    ]
